# ./.tmuxinator.yml

name: sakugahd
root: .

windows:
    - nvim:
          - clear
          - nvim .
    - server:
          - cd server/
          - clear
    - client:
          - cd client/
          - clear
    - bacon: bacon
    - git:
          - clear
          - gs
