DROP TYPE anime_format CASCADE;
DROP TYPE anime_status CASCADE;
DROP TYPE anime_season CASCADE;
DROP TYPE tag_types CASCADE;

DROP TABLE IF EXISTS anime CASCADE;
DROP TABLE IF EXISTS studios CASCADE;
DROP TABLE IF EXISTS anime_studios CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS anime_genres CASCADE;
DROP TABLE IF EXISTS episodes CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS openings CASCADE;
DROP TABLE IF EXISTS endings CASCADE;

DROP TABLE IF EXISTS manga CASCADE;
DROP TABLE IF EXISTS manga_genres CASCADE;
DROP TABLE IF EXISTS themes CASCADE;
DROP TABLE IF EXISTS manga_themes CASCADE;
DROP TABLE IF EXISTS chapters CASCADE;
DROP TABLE IF EXISTS pages CASCADE;

