DROP TYPE show_format CASCADE;
DROP TYPE show_status CASCADE;
DROP TYPE show_season CASCADE;
DROP TABLE IF EXISTS shows CASCADE;

DROP TABLE IF EXISTS studios CASCADE;

DROP TABLE IF EXISTS shows_studios CASCADE;

DROP TABLE IF EXISTS genres CASCADE;

DROP TABLE IF EXISTS shows_genres CASCADE;

DROP TABLE IF EXISTS episodes CASCADE;

DROP TABLE IF EXISTS movies CASCADE;

DROP TABLE IF EXISTS openings CASCADE;

DROP TABLE IF EXISTS endings CASCADE;
